### PR TITLE
♻ — Use a more modern way of installing

### PR DESCRIPTION
**Pull request by ldidry**
- modern Makefile.PL
- centralization of version number: just update it in `lib/MHonArc.pm`
- Add CI (Gitlab CI and Travis CI) ~~=> will fail until #2 is merged~~ (#2 is merged, CI works now)

I’m not sure that I used the better way to centralize the version number. Feel free to comment and propose a better way to do that.

### CODE REVIEW

**Comment by racke** [comment]
Yes, definitely a big step for sanitizing Mhonarc installation :+1:

**Review by dverdin — COMMENTED** [review]
Honestly, the only thing I ever developed instllation for in Perl was Sympa. So it's difficult for me to give you advice on this.
However, I checked your branch out and it install perfectly using the standard Perl command :
```
perl Makefile.PL
make
make test
make install
```
So as far as I know, you Pr is perfectly correct!

**Comment by ldidry** [comment]
Now that I merged #2 and rebased my pending PRs on `develop`, the CI can pass.

I suggest than once this PR is merged, we release the 2.6.20 version, then we can try things that can break things like #4 and #6 (I already created a [2.6.21](https://github.com/sympa-community/MHonArc/milestone/2) milestone for that purpose and assigned those PRs to it)

**Review by ikedas — APPROVED** [review]
`make dist` looks working. Installation seems successful.

**Pull request merged**
